using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ParticleSeedFinderScript : MonoBehaviour
{
    public ParticleSystem ps;

    void Start()
    {
        ps = GetComponent<ParticleSystem>();
        Debug.Log("Generated by: " + gameObject.name + ", Current Seed: " + ps.randomSeed);
    }
}
